import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from 'styles/Home.module.css';
import { Header } from 'pages/component/Header';
import { Footer } from 'pages/component/Footer';
import { Body } from 'pages/component/Body';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header></Header>
      <Body></Body>
      <Footer></Footer>
    </div>
  );
};

export default Home;
