import type { NextPage } from 'next';
import Head from 'next/head';
import styles from 'styles/Home.module.css';
import { Header } from 'component/Header';
import { Footer } from 'component/Footer';
import { Body } from 'component/Body';
import { TodosList } from 'component/TodosList';
import { ChangeEventHandler, useRef, useState } from 'react';

interface Todos {
  id: number;
  label: string;
  isDone: boolean;
}

type Update = {
  update: boolean;
  id: number;
};

const Home: NextPage = () => {
  // 破棄予定
  // const todosList = [
  //   {
  //     title: '今日する',
  //     category: 'today',
  //     todos: ['ESLintのインストール'],
  //   },
  //   {
  //     title: '明日する',
  //     category: 'tomorrow',
  //     todos: ['来週の飲み会の場所を決める', 'Next.jsのチュートリアルを見る'],
  //   },
  //   {
  //     title: '今度する',
  //     category: 'next time',
  //     todos: [],
  //   },
  // ];

  const ref = useRef<HTMLInputElement>(null);
  const [text, setText] = useState('');
  const [todos, setTodos] = useState<Todos[]>([]);
  const [updateButton, setUpdateButton] = useState<Update>({ update: false, id: 0 });

  const toggle: ChangeEventHandler<HTMLInputElement> = (e) => {
    setTodos((prevTodos) => {
      return prevTodos.map((prevTodo) => {
        if (prevTodo.id === Number(e.target.value)) {
          return {
            ...prevTodo,
            isDone: !prevTodo.isDone,
          };
        }

        return prevTodo;
      });
    });
  };

  const input: ChangeEventHandler<HTMLInputElement> = (e) => {
    setText(e.target.value);
  };

  const add = () => {
    setTodos((prevTodos) => {
      return [...prevTodos, { id: Math.random(), label: text, isDone: false }];
    });
    setText('');
  };

  const remove = (index: number): void => {
    const newTodow = [...todos];
    newTodow.splice(index, 1);
    setTodos(newTodow);
  };

  const edit = (id: number): void => {
    setTodos((prevTodos) => {
      return prevTodos.map((prevTodo) => {
        if (prevTodo.id === id) {
          ref.current?.focus();
          setText(prevTodo.label);
          setUpdateButton({ update: true, id: prevTodo.id });
        }
        return { ...prevTodo };
      });
    });
  };

  const update = () => {
    setTodos((prevTodos) => {
      return prevTodos.map((prevTodo) => {
        if (prevTodo.id === updateButton.id) {
          return {
            ...prevTodo,
            label: text,
          };
        }
        return prevTodo;
      });
    });
    setUpdateButton({ update: false, id: 0 });
    setText('');
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header></Header>

      <Body>
        {/* 廃棄予定
        <TodosList todosList={todosList} /> */}

        <ul>
          {todos.map((todo, index) => (
            <li key={todo.id}>
              <input type='checkbox' value={todo.id} onChange={toggle} checked={todo.isDone} />
              <button onClick={() => edit(todo.id)}>{todo.label}</button>
              <button className='border border-red-500' onClick={() => remove(index)}>
                削除
              </button>
            </li>
          ))}
        </ul>
      </Body>

      <Footer>
        <div>
          <input className='border border-gray' value={text} onChange={input} ref={ref} type='text' />
          <button onClick={() => (updateButton.update ? update() : add())}>追加</button>
        </div>
      </Footer>
    </div>
  );
};

export default Home;
