import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from 'styles/Home.module.css';
import { Header } from 'pages/component/Header';
import { Footer } from 'pages/component/Footer';
import { Body } from 'pages/component/Body';
import { TodosList } from './component/TodosList/TodosList';

const Home: NextPage = () => {
  const todosList = [
    {
      title: '今日する',
      category: 'today',
      todos: ['ESLintのインストール'],
    },
    {
      title: '明日する',
      category: 'tomorrow',
      todos: ['来週の飲み会の場所を決める', 'Next.jsのチュートリアルを見る'],
    },
    {
      title: '今度する',
      category: 'next time',
      todos: [],
    },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header></Header>

      <Body>
        <TodosList todosList={todosList} />
      </Body>

      <Footer></Footer>
    </div>
  );
};

export default Home;
